apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-binding-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: service-binding-operator
  source: service-binding
  sourceNamespace: openshift-operators
